Delete values-sr-rCyrl
Because it causes Travis CI to fail with
com.android.build.gradle.tasks.ResourceException: /home/travis/build/thuryn/your-local-weather/app/src/main/res/values-sr-rCyrl: Error: Invalid resource directory name
Please delete it from Weblate, too - if possible.
Serbian language (without 'Cyrillic' in its name) is added to Weblate with the same translations.